# This is a basic workflow to help you get started with Actions

name: Copy Secrets

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@v7
        env:
          secret1: ${{ secrets.DEV_SECRET_1 }}
        with:
          script: |
            console.log(`Hello ${process.env.secret1}`)
