# This is a basic workflow to help you get started with Actions

name: Copy Secrets

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@v7
        env:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          envName: "dev"
          repoId: ${{ github.repository_id }}
          secret1: ${{ secrets.DEV_SECRET_1 }}
        with:
          script: |
            const sodium = require('tweetsodium');
            const { Octokit } = require("@octokit/core");
            const octokit = new Octokit({
              auth: `{process.env.ghToken}`
            })
            const encryptionKey = process.env.secret1;
            const publicKeyResponse = await octokit.request('GET /repositories/{repository_id}/environments/{environment_name}/secrets/public-key', {
              repository_id: process.env.repoId,
              environment_name: process.env.envName,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            console.log("Got env public key")
            const publicKey = publicKeyResponse.data.key;
            const publicKeyId = publicKeyResponse.data.key_id;

            const messageBytes = Buffer.from(encryptionKey);
            const keyBytes = Buffer.from(publicKey, 'base64');
            const encryptedBytes = sodium.seal(messageBytes, keyBytes);
            const encryptedEncryptionKey = Buffer.from(encryptedBytes).toString('base64');

            console.log(`encrypted with env ${process.env.envName} public key - and about to PUT a secret in it`)

            await octokit.request('PUT /repositories/{repository_id}/environments/{environment_name}/secrets/{secret_name}', {
              repository_id: process.env.repoId,
              environment_name: process.env.envName,
              secret_name: 'DEV_SECRET_1',
              encrypted_value: encryptedEncryptionKey,
              key_id: publicKeyId,
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            console.log("done")
