name: email-notification

on:
  workflow_dispatch:

jobs:
  playwright_tests:
    name: test-1
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  status:
    name: Status
    runs-on: ubuntu-latest
    needs: [ playwright_tests ]
    if: ${{ !failure() && !cancelled() }}  
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.fastmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: daniel@danielhabib.co.il
          from: Github Actions Admin
          html_body: |
            # Test Run Summary
            
            ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
            
