name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup_matrix:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      matrix: steps.set-matrix.outputs.result

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: set-matrix
        uses: actions/github-script@v7
        with: 
          script: |
            const qaRegex = /qa.*/;
            const matrix = {
              include: [
                {
                  suite_name: "a",
                  test_command: "hello a"                  
                },
                {
                  suite_name: "b",
                  test_command: "hello b"
                }
              ]
            };
            if (qaRegex.test(github.head_ref)) {
              matrix.include.push({
                suite_name: "c",
                test_command: "hello c"
              });
            }
            return matrix;
      - name: Get result
        run: echo "${{steps.set-matrix.outputs.result}}"
  run_tests:
    name: ${{ matrix.suite_name }}
    runs-on: ubuntu-latest
    needs: setup_matrix
    strategy:
      matrix: ${{ needs.setup_matrix.outputs.matrix }}
    steps:
      - name: run the test
        run: echo ${{ matrix.test_command }}
