name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'config-path = ${{ inputs.config-path }}'
