name: reusable caller

on:
  pull_request

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Format all
        run: echo "formatting ..."
  call-workflow-passing-data:
    uses: ./.github/workflows/workflow-b.yml
    with:
      config-path: "testing..."
